# Generated by Django 4.1.2 on 2025-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=250)),
                ('campus', models.CharField(max_length=250, unique=True)),
                ('abreviation', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
