# Generated by Django 4.2.24 on 2025-10-27 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='bank_account_setup',
            field=models.BooleanField(default=False, help_text='Whether bank account is set up for payments'),
        ),
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='manager',
            name='payment_currency',
            field=models.CharField(blank=True, help_text='Currency for payments (e.g., GHS, USD, EUR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='paystack_subaccount_id',
            field=models.CharField(blank=True, help_text='Paystack subaccount ID for payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
