# Generated by Django 6.0.8 on 2026-08-09 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived'), ('removed', 'Removed')], default='draft', max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('full', 'Full'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('shared', 'Shared'), ('two_in_room', 'Two in room'), ('three_in_room', 'Three in room'), ('four_in_room', 'Four in room'), ('dormitory', 'Dormitory'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('other', 'Other')], max_length=32)),
                ('gender_restriction', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('available_slots', models.PositiveSmallIntegerField(default=0)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_period', models.CharField(choices=[('month', 'Month'), ('semester', 'Semester'), ('academic_year', 'Academic year'), ('year', 'Year')], default='academic_year', max_length=20)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agent_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('manager', 'Manager'), ('porter', 'Porter'), ('owner', 'Owner'), ('caretaker', 'Caretaker'), ('agent_verified', 'Agent verified'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agents.agentprofile')),
                ('amenities', models.ManyToManyField(blank=True, related_name='listings', to='listings.amenity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=180)),
                ('property_type', models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('chamber_and_hall', 'Chamber and hall'), ('single_room', 'Single room'), ('other', 'Other')], default='hostel', max_length=32)),
                ('gender_policy', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.property'),
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='listings/images/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_listing_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['listing', 'is_cover'], name='listings_li_listing_7c3dcd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='listings_pr_name_992ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='listings_pr_propert_36edbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('area', 'name'), name='unique_property_per_area'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'moderation_status'], name='listings_li_status_597569_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['availability_status', 'last_confirmed_at'], name='listings_li_availab_a0976e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_amount'], name='listings_li_price_a_b62ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['room_type'], name='listings_li_room_ty_56e6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='listings_li_created_740656_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('available_slots__lte', models.F('capacity'))), name='available_slots_lte_capacity'),
        ),
        migrations.AddIndex(
            model_name='savedlisting',
            index=models.Index(fields=['student', 'created_at'], name='listings_sa_student_2ca8c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedlisting',
            constraint=models.UniqueConstraint(fields=('student', 'listing'), name='unique_saved_listing_per_student'),
        ),
    ]
