# Generated by Django 4.2.14 on 2025-10-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='accepts_bookings',
            field=models.BooleanField(default=True, help_text='Whether this hostel accepts direct bookings (Book button) or only reservations'),
        ),
    ]
