# Generated by Django 4.2.24 on 2025-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0002_hostel_accepts_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='pricing_period',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', help_text='Whether prices are displayed per month or per year', max_length=10),
        ),
    ]
