# Generated by Django 4.2.24 on 2025-10-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0003_hostel_pricing_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='pricing_period',
        ),
    ]
