# Generated by Django 4.1.2 on 2025-09-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
        ),
        migrations.CreateModel(
            name='SplitPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(choices=[('percentage', 'Percentage Split'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('manager_percentage', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage for manager (e.g., 80.00 for 80%)', max_digits=5)),
                ('platform_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage for platform (e.g., 20.00 for 20%)', max_digits=5)),
                ('manager_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for manager', max_digits=10, null=True)),
                ('platform_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for platform', max_digits=10, null=True)),
                ('platform_subaccount_code', models.CharField(blank=True, help_text='Paystack subaccount code for platform', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
            options={
                'unique_together': {('manager',)},
            },
        ),
    ]
