# Generated by Django 4.1.2 on 2025-09-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitPaymentConfig',
        ),
    ]
