# Generated by Django 4.1.2 on 2025-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_account', '0002_delete_splitpaymentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='platform_fee_kobo',
            field=models.PositiveIntegerField(default=50000, help_text='Platform fee in kobo (e.g., 50000 = ₦500)'),
        ),
    ]
