# Generated by Django 4.1.2 on 2025-09-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_account', '0003_paymentaccount_platform_fee_kobo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='platform_fee_kobo',
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='platform_share_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Platform share percentage (e.g., 5.00 = 5%)', max_digits=5),
        ),
    ]
