# Generated by Django 4.2.24 on 2025-09-24 00:28
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('payment_account', '0004_remove_paymentaccount_platform_fee_kobo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='platform_share_percentage',
            field=models.DecimalField(
                max_digits=5,
                decimal_places=2,
                default=5.00,
                help_text="Platform share percentage (e.g., 5.00 = 5%)",
            ),
        ),
    ]
