# Generated by Django 6.0.8 on 2026-08-09 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('business_name', models.CharField(max_length=180)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=32)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('profile_photo', models.FileField(blank=True, upload_to='agents/profile_photos/')),
                ('verification_status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='unsubmitted', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('listing_freshness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operating_areas', models.ManyToManyField(blank=True, related_name='agents', to='locations.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='agents/documents/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_agent_documents', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('submitted_notes', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='agents.agentprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['verification_status'], name='agents_agen_verific_73e42d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['business_name'], name='agents_agen_busines_0b5ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status', 'created_at'], name='agents_veri_status_4a13b2_idx'),
        ),
    ]
