import { ArrowLeft, Check, CircleAlert, Eye, FileCheck2, UserRound, X } from 'lucide-react'
import type { Agent } from '../../../api/mockApi'
import type { AppProps } from '../../../app/types'
import { Badge, EmptyState, Fact, Field, FormSection } from '../../../components/shared/Primitives'
import { initials, verificationTone } from '../../../lib/uiHelpers'
import '../AdminPages.css'

export function AdminAgentDetail(props: AppProps & { id: string }) {
  const agent = props.db.agents.find((a) => a.id === props.id)
  if (!agent) return <EmptyState icon={<UserRound />} title="Agent not found" body="This record is unavailable." action="Back to agents" onAction={() => props.navigate('/admin/agents')} />
  const decide = (verification: Agent['verification']) => props.mutate(`Agent marked ${verification.toLowerCase()}`, (draft) => { const item = draft.agents.find((a) => a.id === agent.id); if (item) item.verification = verification })
  return <div className="page"><button className="back-button" onClick={() => props.navigate('/admin/agents')}><ArrowLeft size={17} />Back to agents</button><div className="review-header"><div className="profile-avatar">{initials(agent.name)}</div><div><Badge tone={verificationTone(agent.verification)}>{agent.verification}</Badge><h1>{agent.name}</h1><p>{agent.business} · Joined {agent.joined}</p></div><div className="decision-actions"><button className="btn secondary danger-text" onClick={() => decide('Rejected')}><X size={17} />Reject</button><button className="btn primary" onClick={() => decide('Verified')}><Check size={17} />Approve agent</button></div></div><div className="review-layout"><div><FormSection title="Identity evidence" description={`${agent.documents.length} documents submitted`}><div className="evidence-grid">{agent.documents.map((d) => <button key={d}><FileCheck2 /><span><strong>{d}</strong><small>PDF · Backend document record</small></span><Eye /></button>)}{!agent.documents.length && <EmptyState icon={<FileCheck2 />} title="No evidence submitted" body="This agent has not started verification." />}</div></FormSection><FormSection title="Account activity" description="Trust indicators from live platform use."><div className="key-facts"><Fact label="Response rate" value={`${agent.responseRate}%`} /><Fact label="Freshness score" value={`${agent.freshnessScore}%`} /><Fact label="Listings" value={String(props.db.listings.filter((l) => l.agentId === agent.id).length)} /><Fact label="Reports" value={String(props.db.reports.filter((r) => props.db.listings.find((l) => l.id === r.listingId)?.agentId === agent.id).length)} /></div></FormSection></div><aside className="decision-panel"><span className="eyebrow">Reviewer checklist</span>{['Identity name matches', 'Contact number confirmed', 'Operating areas plausible', 'Evidence is legible'].map((x) => <label className="check" key={x}><input type="checkbox" defaultChecked={agent.verification === 'Verified'} />{x}</label>)}<Field label="Decision notes"><textarea rows={5} placeholder="Required for rejection or suspension" /></Field><p><CircleAlert size={15} />Every decision is written to the audit log.</p></aside></div></div>
}
