import { useState } from 'react'
import { Building2, Check, EyeOff, Search, Trash2 } from 'lucide-react'
import type { Listing } from '../../../api/mockApi'
import type { AppProps } from '../../../app/types'
import { Badge, Drawer, Field, PageHeader, Review } from '../../../components/shared/Primitives'
import { money } from '../../../lib/uiHelpers'
import '../AdminPages.css'

export function AdminListings(props: AppProps) {
  const [selected, setSelected] = useState<Listing | null>(null)
  const moderate = (listing: Listing, moderation: Listing['moderation'], status?: Listing['status']) => props.mutate(`Listing marked ${moderation.toLowerCase()}`, (draft) => { const item = draft.listings.find((l) => l.id === listing.id); if (item) { item.moderation = moderation; if (status) item.status = status } })
  return <div className="page"><PageHeader eyebrow="Content quality" title="Listing moderation" description="Inspect freshness, reports, and publish state across all agents." /><div className="toolbar"><div className="input-with-icon"><Search size={17} /><input placeholder="Search listing or agent" /></div><select><option>All moderation</option><option>Pending</option><option>Flagged</option><option>Approved</option></select><span className="result-count">{props.db.listings.length} listings</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Listing</th><th>Agent</th><th>Moderation</th><th>Freshness</th><th>Reports</th><th></th></tr></thead><tbody>{props.db.listings.map((l) => <tr key={l.id}><td><div className="table-identity">{l.image ? <img src={l.image} alt="" /> : <span className="image-placeholder"><Building2 /></span>}<span><strong>{l.title}</strong><small>{l.area} · {l.campus}</small></span></div></td><td>{l.agentName}</td><td><Badge tone={l.moderation === 'Approved' ? 'success' : l.moderation === 'Flagged' ? 'danger' : 'warning'}>{l.moderation}</Badge></td><td>{l.freshness}</td><td>{props.db.reports.filter((r) => r.listingId === l.id).length}</td><td><button className="btn secondary small" onClick={() => setSelected(l)}>Inspect</button></td></tr>)}</tbody></table></div>{selected && <Drawer title="Moderate listing" close={() => setSelected(null)}>{selected.image ? <img className="drawer-image" src={selected.image} alt={selected.title} /> : <div className="drawer-image image-placeholder"><Building2 /></div>}<div><Badge tone={selected.moderation === 'Approved' ? 'success' : 'warning'}>{selected.moderation}</Badge><h2>{selected.title}</h2><p>{selected.description}</p></div><div className="review-list"><Review label="Agent" value={selected.agentName} /><Review label="Availability" value={`${selected.availability} · ${selected.freshness}`} /><Review label="Price" value={`${money.format(selected.price)} / ${selected.period}`} /></div><Field label="Moderation notes"><textarea rows={4} placeholder="Explain high-impact decisions" /></Field><div className="drawer-actions three"><button className="btn secondary danger-text" onClick={() => moderate(selected, 'Rejected', 'Removed')}><Trash2 size={16} />Remove</button><button className="btn secondary" onClick={() => moderate(selected, 'Flagged', 'Unpublished')}><EyeOff size={16} />Hide</button><button className="btn primary" onClick={() => moderate(selected, 'Approved', 'Published')}><Check size={16} />Approve</button></div></Drawer>}</div>
}
