import { useState } from 'react'
import { CheckCircle2, LockKeyhole, Search } from 'lucide-react'
import type { Database } from '../../../api/mockApi'
import type { AppProps } from '../../../app/types'
import { Badge, Drawer, PageHeader, Review } from '../../../components/shared/Primitives'
import { initials } from '../../../lib/uiHelpers'
import '../AdminPages.css'

export function AdminUsers(props: AppProps) {
  const [selected, setSelected] = useState<Database['users'][number] | null>(null)
  return <div className="page"><PageHeader eyebrow="Accounts" title="Platform users" description="Inspect role, verification, and account state without impersonation." /><div className="toolbar"><div className="input-with-icon"><Search size={17} /><input placeholder="Search name or email" /></div><select><option>All roles</option><option>Student</option><option>Agent</option><option>Admin</option></select><span className="result-count">{props.db.users.length} users</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Email</th><th>Status</th><th>Last active</th><th></th></tr></thead><tbody>{props.db.users.map((u) => <tr key={u.id}><td><div className="person-cell"><span className="avatar-sm">{initials(u.name)}</span><strong>{u.name}</strong></div></td><td>{u.role}</td><td>{u.verified ? <span className="verified"><CheckCircle2 size={14} />Verified</span> : <Badge tone="warning">Unverified</Badge>}</td><td><Badge tone={u.status === 'Active' ? 'success' : 'danger'}>{u.status}</Badge></td><td>{u.lastActive}</td><td><button className="btn secondary small" onClick={() => setSelected(u)}>View</button></td></tr>)}</tbody></table></div>{selected && <Drawer title="Account details" close={() => setSelected(null)}><div className="account-profile"><span className="profile-avatar">{initials(selected.name)}</span><div><h2>{selected.name}</h2><p>{selected.email}</p><Badge tone={selected.status === 'Active' ? 'success' : 'danger'}>{selected.status}</Badge></div></div><div className="review-list"><Review label="Role" value={selected.role} /><Review label="Email verification" value={selected.verified ? 'Verified' : 'Pending'} /><Review label="Last active" value={selected.lastActive} /></div><div className="info-callout"><LockKeyhole />Impersonation is intentionally unavailable in the MVP.</div><button className="btn secondary danger-text full" onClick={() => props.mutate(selected.status === 'Active' ? 'Account suspended' : 'Account reactivated', (draft) => { const item = draft.users.find((u) => u.id === selected.id); if (item) item.status = item.status === 'Active' ? 'Suspended' : 'Active' })}>{selected.status === 'Active' ? 'Suspend account' : 'Reactivate account'}</button></Drawer>}</div>
}
