# Generated by Django 6.0.8 on 2026-08-09 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('student_phone', models.CharField(max_length=32)),
                ('preferred_contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email')], default='whatsapp', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing scheduled'), ('negotiating', 'Negotiating'), ('closed_won', 'Closed won'), ('closed_lost', 'Closed lost'), ('spam', 'Spam')], default='new', max_length=24)),
                ('agent_notes', models.TextField(blank=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='agents.agentprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='listings.listing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing scheduled'), ('negotiating', 'Negotiating'), ('closed_won', 'Closed won'), ('closed_lost', 'Closed lost'), ('spam', 'Spam')], max_length=24)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing scheduled'), ('negotiating', 'Negotiating'), ('closed_won', 'Closed won'), ('closed_lost', 'Closed lost'), ('spam', 'Spam')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_status_events', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['student', 'status'], name='inquiries_i_student_b90437_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['agent', 'status'], name='inquiries_i_agent_i_93183c_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['listing', 'created_at'], name='inquiries_i_listing_28f59e_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['next_follow_up_at'], name='inquiries_i_next_fo_1983f8_idx'),
        ),
    ]
