# Generated by Django 4.2.24 on 2025-11-02 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(blank=True, help_text='Store ID (to be linked when Store model exists)', null=True)),
                ('location', models.CharField(blank=True, help_text='Auto-populated from consumer.hostel.campus if user is a consumer', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepreneur',
                'verbose_name_plural': 'Entrepreneurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
