# Generated by Django 4.2.24 on 2025-11-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store/Business name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Store description', null=True)),
                ('location', models.CharField(blank=True, help_text='Store location/campus', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='store_id',
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Commodity name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Commodity description', null=True)),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', help_text='Commodity type: product or service', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the commodity', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='entrepreneurs.store')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store owned by this entrepreneur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneurs', to='entrepreneurs.store'),
        ),
    ]
