# Generated by Django 4.2.24 on 2025-11-08 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrepreneurs', '0002_store_remove_entrepreneur_store_id_commodity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Store cover photo/banner', null=True, upload_to='store_covers/'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the commodity', null=True, upload_to='commodity_images/'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='logo',
            field=models.ImageField(blank=True, help_text='Store logo image', null=True, upload_to='store_logos/'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Transaction price', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee deducted from transaction', max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Net profit after service fee (price - service_fee)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Transaction status', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Date of transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(blank=True, help_text='Consumer who made the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product/service sold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='entrepreneurs.commodity')),
                ('store', models.ForeignKey(help_text='Store that made the sale', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='entrepreneurs.store')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['store', '-transaction_date'], name='entrepreneu_store_i_57c0fa_idx'), models.Index(fields=['consumer', '-transaction_date'], name='entrepreneu_consume_09fa32_idx'), models.Index(fields=['product', '-transaction_date'], name='entrepreneu_product_2a1054_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommodityClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, help_text='When the click occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for analytics', null=True)),
                ('commodity', models.ForeignKey(help_text='Commodity that was clicked/viewed', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='entrepreneurs.commodity')),
                ('user', models.ForeignKey(blank=True, help_text='User who clicked (optional, for analytics)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commodity Click',
                'verbose_name_plural': 'Commodity Clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['commodity', '-clicked_at'], name='entrepreneu_commodi_618f49_idx')],
            },
        ),
    ]
