# Generated by Django 4.2.24 on 2025-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0003_commodity_cover_photo_commodity_image_commodity_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='category_slug',
            field=models.CharField(blank=True, help_text="Category slug (e.g., 'electronics', 'fashion', 'food')", max_length=100, null=True),
        ),
    ]
