# Generated by Django 4.2.24 on 2025-11-09 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrepreneurs', '0007_move_store_images_to_store_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverer',
            name='unique_deliverer_user',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='entrepreneu_deliver_3f1f15_idx',
            old_name='entrepreneu_deliver_trans_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='entrepreneu_status_d14999_idx',
            old_name='entrepreneu_status_del_idx',
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee deducted from transaction (1.5% of price)', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='deliverer',
            unique_together={('user',)},
        ),
    ]
