# Generated by Django 6.0.8 on 2026-08-09 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('abbreviation', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='locations.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='locations.campus')),
            ],
            options={
                'ordering': ['campus__name', 'name'],
                'indexes': [models.Index(fields=['name'], name='locations_a_name_3c7ce7_idx')],
                'constraints': [models.UniqueConstraint(fields=('campus', 'name'), name='unique_area_per_campus')],
            },
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['name'], name='locations_c_name_a3bcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['abbreviation'], name='locations_c_abbrevi_7f9e16_idx'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='unique_campus_per_region'),
        ),
    ]
