# Generated by Django 6.0.8 on 2026-08-09 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=160)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('paystack', 'Paystack')], default='manual', max_length=16)),
                ('provider_reference', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('wants_account_history', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='listings.listing')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest_email', 'created_at'], name='payments_pa_guest_e_45db01_idx'), models.Index(fields=['student', 'created_at'], name='payments_pa_student_978a1e_idx'), models.Index(fields=['listing', 'status'], name='payments_pa_listing_16cc65_idx'), models.Index(fields=['provider_reference'], name='payments_pa_provide_6dd94b_idx')],
            },
        ),
    ]
